
spring:
  application:
    name: admin-service
  devtools:
    livereload:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1312
    url: jdbc:postgresql://localhost:5432/spring_cloud_ex1

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
