spring:
  application:
    name: manga-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_cloud_ex_1
    username: postgres
    password: 1312
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka